### ISSUE TITLE
 memory occupation of graphics card

### ISSUE THREAD

**Issue by zhangguanghui1** [overlappredator/OverlapPredator#1]
Thank you your work. 
The memory occupation of graphics card has a large fluctuation, is there a way to fix it?

**Comment by zhangguanghui1** [comment]
I don't know why the  memory occupation of graphics card of an iter suddenly goes out of memory. I hope to get your reply. Thank you very much.

**Comment by ShengyuH** [comment]
> Thank you your work.
> The memory occupation of graphics card has a large fluctuation, is there a way to fix it?

hi, Thank you for your interest in our work. We are working on this memory problem, please stay tuned.

Shengyu

**Comment by ShengyuH** [comment]
Close due to inactivity. Please reopen if you find any solutions to this problem.
