### ISSUE TITLE
How long is the training?

### ISSUE THREAD

**Issue by Codefmeister** [overlappredator/OverlapPredator#13]
Thanks for your awesome work. Inspired by it greatly, I want to do some further research on it.  However my hardware condition is not so good.
So could you plz tell me the training time on 3dMatch? num and type of the GPUs?
Thanks in advance.

**Comment by ShengyuH** [comment]
hi,

I once trained using 1 RTX 2080Ti/RTX 3090, each epoch took around 2/1.5 hours, so in total around 2 days.

**Comment by Codefmeister** [comment]
Thank you!

**Comment by qsisi** [comment]
Hey, there

I also noticed that the param: **max_epoches** of this KPConv version differs from the other MinkConv-based version:
   
KPConv-based : ~40 epoches
MinkConv-baed: ~100 epoches

And they both need about 2 hours to finish training one single epoch, there is a **HUGE** time difference between these two versions, it's a little bit strange to me, but anyway, the final performance of these two seems to be the same. 

:)

**Comment by ShengyuH** [comment]
hi,

- I train ME version after CVPR, I don't have time pressure and it's a single experiment, so I just train it for 100 epochs, as FCGF did. 
- The message of this experiment is that "Predator is flexible regarding the backbone networks". So training two backbones differently doesn't harm this argument. To really compare two backbones, we need to design fair experiments.
