### ISSUE TITLE
Can we get a repeatable result?

### ISSUE THREAD

**Issue by fukexue** [overlappredator/OverlapPredator#16]
I'm sorry to disturb you. When I run evaluate_predator.py file, the final recall results of two runs are inconsistent. Is this normal?

**Comment by ShengyuH** [comment]
hi,

Do you mean you didn't get exact same numbers? Yes this is normal as we have randomness in RANSAC, but I wouldn't expect the difference to be big. Can you also post your results here? Then we can have a look.


Shengyu

**Comment by fukexue** [comment]
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.967	¦ 0.967	¦ 1.824	¦ 0.051	¦ 449¦
Home 1	¦ 0.953	¦ 0.953	¦ 1.885	¦ 0.056	¦ 106¦
Home 2	¦ 0.723	¦ 0.723	¦ 2.301	¦ 0.067	¦ 159¦
Hotel 1	¦ 0.973	¦ 0.973	¦ 1.874	¦ 0.059	¦ 182¦
Hotel 2	¦ 0.923	¦ 0.923	¦ 1.755	¦ 0.057	¦  78¦
Hotel 3	¦ 0.846	¦ 0.846	¦ 2.472	¦ 0.056	¦  26¦
Study	¦ 0.846	¦ 0.846	¦ 2.107	¦ 0.078	¦ 234¦
MIT Lab	¦ 0.711	¦ 0.711	¦ 1.601	¦ 0.073	¦  45¦
Mean precision: 0.868: +- 0.098
Weighted precision: 0.900
Mean median RRE: 1.977: +- 0.274
Mean median RTE: 0.062: +- 0.009
Inlier ratio w_mutual: 0.499 : +- 0.047
Feature match recall w_mutual: 0.967 : +- 0.014
ransac_with_mutual: False, inlier_ratio_threshold0.05
Inlier ratio wo_mutual: 0.392 : +- 0.042
Feature match recall wo_mutual: 0.953 : +- 0.027
ransac_with_mutual: False, inlier_ratio_threshold0.05

**Comment by fukexue** [comment]
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.960	¦ 0.960	¦ 1.806	¦ 0.049	¦ 449¦
Home 1	¦ 0.953	¦ 0.953	¦ 1.665	¦ 0.054	¦ 106¦
Home 2	¦ 0.742	¦ 0.742	¦ 2.378	¦ 0.073	¦ 159¦
Hotel 1	¦ 0.967	¦ 0.967	¦ 1.937	¦ 0.066	¦ 182¦
Hotel 2	¦ 0.936	¦ 0.936	¦ 1.834	¦ 0.069	¦  78¦
Hotel 3	¦ 0.846	¦ 0.846	¦ 2.413	¦ 0.047	¦  26¦
Study	¦ 0.846	¦ 0.846	¦ 2.144	¦ 0.076	¦ 234¦
MIT Lab	¦ 0.800	¦ 0.800	¦ 1.455	¦ 0.072	¦  45¦
Mean precision: 0.881: +- 0.079
Weighted precision: 0.903
Mean median RRE: 1.954: +- 0.315
Mean median RTE: 0.063: +- 0.011
Inlier ratio w_mutual: 0.499 : +- 0.047
Feature match recall w_mutual: 0.967 : +- 0.014
Inlier ratio wo_mutual: 0.392 : +- 0.042
Feature match recall wo_mutual: 0.953 : +- 0.027

**Comment by fukexue** [comment]
Above is the result of two runs

**Comment by zgojcic** [comment]
@fukexue thanks for updating this issue. You can observe that the all the metrics that are not RANSAC dependent (Inlier ratio, feature match recall,...) are the same in both runs. The randomness comes from the open3D implementation of RANSAC, which has randomness in sampling the points (see e.g. https://github.com/intel-isl/Open3D/issues/288) and the seed can unfortunately not be set. This is a problem of open3d and not our method.

If you require deterministic results a different implementation of RANSAC in which the random seed can be set should be used.

Hope that this makes sense. 

Best,
Zan

**Comment by fukexue** [comment]
Thank you very much for your answer. I'm not sure about this situation before. Your answer has helped me a lot. Thank you very much.

**Comment by zgojcic** [comment]
No problem. If you have any other questions, open a new issue. 

Zan
