### ISSUE TITLE
Error in loading data with lower points

### ISSUE THREAD

**Issue by fpvc040** [overlappredator/OverlapPredator#18]
Hi,
I am trying to run this example with my own data (.pts). But it isn't optimized to do so. The demo files have around 25,000 points, and it runs successfully, but with open3D (as it doesn't load it into torch), during the operations it asks for about 316 GB of GPU for ~20,000 points. I wanted to try and change the data format to .pth, is there a way to do so?

**Comment by fpvc040** [comment]
For anyone having this issue, I resolved this issue by downscaling the magnitude of points. Basically, multiply your point cloud with a decimal to lower the magnitude of the point data

**Comment by PranayShirodkar** [comment]
> For anyone having this issue, I resolved this issue by downscaling the magnitude of points. Basically, multiply your point cloud with a decimal to lower the magnitude of the point data

I observed the same problem as you, and your suggestion worked! Thank you very much for posting this. Do you know why downscaling the point cloud is reducing the memory requirements? Since the number of points is the same, I did not expect downscaling to matter.
