### ISSUE TITLE
Question about test

### ISSUE THREAD

**Issue by JikC** [overlappredator/OverlapPredator#22]
Thanks for your great work, I have two question:

1. I already trained on indoor dataset. If I want to test, should I change the path "weights/indoor.pth" in "configs/test/indoor.yaml " before run "python main.py configs/test/indoor.yaml"? 

2. What information saved in "snapshot/model"? Is it the model I trained? And how to use it?

Looking forward to your reply. 
Best regards

**Comment by ShengyuH** [comment]
hi,

1. yes, you should point ```pretrain``` to your weights file
2. It saves description of the model. It's for reference, especially when you want to plot the models

Best,
Shengyu

**Comment by JikC** [comment]
Could you please tell me where the trained weight will be placed by default？Is it snapshot/indoor/checkpoints/model_best_recall.pth? How about model_best_loss.pth?

**Comment by ShengyuH** [comment]
You can take either of them.

**Comment by JikC** [comment]
Thank you very much!!!
