### ISSUE TITLE
about 3DLoMatch test

### ISSUE THREAD

**Issue by fukexue** [overlappredator/OverlapPredator#24]
Hello, I'm sorry to bother you. Do I need to retrain when test 3DLoMatch, or do I use the model trained by 3DMatch to test it directly on 3DMatch model. We look forward to your reply.

**Comment by ShengyuH** [comment]
hi,

"Do I need to retrain when test 3DLoMatch" ---- No

"or do I use the model trained by 3DMatch to test it directly on 3DMatch model." ---- Yes
