### ISSUE TITLE
Question about visualization of ground truth

### ISSUE THREAD

**Issue by JikC** [overlappredator/OverlapPredator#25]
Sorry for bother you again.

I wonder know how to visualize the ground truth transformation of two pairs?

Looking forward to your reply.

**Comment by JikC** [comment]
And what is 'neighborhood_limits'? What its purpose?

**Comment by ShengyuH** [comment]
hi,

To answer your question: 

1. check our demo.py to see the visualisations
2. KPConv uses "neighborhood_limits" to control the neighborhood size of each point such that in some extremely dense cases, memory doesn't blow up.

**Comment by JikC** [comment]
Sorry, I know the result of 'demo.py' is the registration result of your model. But I want to know how they should have been registered. For example, 'cloud_bin_9' and 'cloud_bin_0', which 'txt' is the tsfm of them?
