### ISSUE TITLE
Problems encountered in the reproduction process

### ISSUE THREAD

**Issue by Hui-design** [overlappredator/OverlapPredator#28]
Hi, thank you for your amazing work.
I am reproducing your work recently, and amazed by your clear and novel ideas and detailed experiments, but I now encounter two problems:
1. Generalization ability. FMR from 3dmatch to ETH is less than 30%. Even if the KPconv radius and kernel points weights are adjusted like D3Feat. Is this because the overlap module is sensitive to data distribution?
2. Speed. Our test found that D3Feat is twice as fast as PREDATOR regarding inference time. And in the report of your paper, the decoder time is only 1ms, but D3Feat uses 63ms. We think this is unreasonable because your decoder codes are similar.
If you have time, can you help me solve these two problems?

Best,
Canhui

**Comment by ShengyuH** [comment]
hi,

1. I guess an sanity check could be visualising the overlapping scores and see if it's working properly. I didn't really check the generalisation ability, so it's difficult for me to say which part might be wrong, or our model just doesn't generalise. I think by nature, fully convolutional backbones are just sensitive to point cloud densities(FCGF doesn't generalise, D3Feat only generalises with some hack).

2. In the bottleneck, our overlap attention module outputs features with dimension 256(D3Feat works with 1024-D features), this substantially reduces the computational load of the decoder part. Therefore, the decoder is similar, but ours is way smaller. In addition, we use PyTorch implementation of D3Feat for fair comparison. 

Best,
Shengyu

**Comment by ShengyuH** [comment]
Close due to inactivity. Please reopen if you encounter further issues.
