### ISSUE TITLE
Can you give the data from 0.01 to 0.02 in 3DLoMatch?

### ISSUE THREAD

**Issue by QWTforGithub** [overlappredator/OverlapPredator#30]
Hi,I would like to make some experimental comparisons according to your work. Could you give me the Feat Macthing Ratio from 0.00 to 0.20 in 3DLoMatch? The results I run by myself may not meet the requirements of the results you run, so I hope you can give me, thank you.

Looking forward your reply.

**Comment by zgojcic** [comment]
Hi @QWTforGithub,

we do not have these results saved, so we would have to rerun the experiments. Please try it out first yourself and let us know if you have some problems recreating the numbers.

Best
Zan

**Comment by zgojcic** [comment]
Closing this issue for now, please open a new one if you have further questions.
