### ISSUE TITLE
Which metrics for odometryKITTI reported in the paper?

### ISSUE THREAD

**Issue by Xylon-Sean** [overlappredator/OverlapPredator#31]
Hi , Shengyu

The outputs from kitti test code contain `rot_mean` `rot_median` `trans_rmse` `trans_rmedse` `rot_std` `trans_std`

Could you tell which metrics correspond to the `RTE` and `RRE` in the Table 5 ( OdometryKITTI )

Thank you so much
: )

**Comment by ShengyuH** [comment]
hi,

We report ```rot_mean``` as ```RRE``` and ```trans_rmse``` as ```RTE```.

best,
Shengyu
