### ISSUE TITLE
Can this be used to enhance object detection?

### ISSUE THREAD

**Issue by FlyerMaxwell** [overlappredator/OverlapPredator#32]
Thanks for your open source code. Can this work be used to merge frames of a time series to get a higher dectection accuracy. For example, I have a lidar with 16 lines. Can I use this work to combine two frames to simulate a Lidar with 32 lines?

**Comment by ShengyuH** [comment]
hi,

Point cloud registration does exactly the job of "merging frames", and it has been confirmed in nuScenes paper that we can get a higher accuracy by merging multiple frames. However, you will have to adapt our model to your data sparsity for robust and accurate registration.

**Comment by FlyerMaxwell** [comment]
Thanks for your reply! I am pretty new about point cloud registration. Actually, I am carring a wireless related project. and I need to use Lidar as a ground truth. My lidar data is pretty simliar to KITTI so I want to try overlapPredator with my own Lidar of 16 lines. 

By inplement your project and run
```
python scripts/demo.py configs/test/indoor.yaml
```
I see that two frames has been merged with a transform matrix.  Is there a similar visualization demo with KITTI?
