### ISSUE TITLE
 Is there a similar visualization demo with KITTI？

### ISSUE THREAD

**Issue by FlyerMaxwell** [overlappredator/OverlapPredator#33]
Thanks for your reply! I am pretty new about point cloud registration. Actually, I am carring a wireless related project. and I need to use Lidar as a ground truth. My lidar data is pretty simliar to KITTI so I want to try overlapPredator with my own Lidar of 16 lines. 

By inplement your project and run
```
python scripts/demo.py configs/test/indoor.yaml
```
I see that two frames has been merged with a transform matrix.  Is there a similar visualization demo with KITTI?

_Originally posted by @FlyerMaxwell in https://github.com/overlappredator/OverlapPredator/issues/32#issuecomment-968691127_

**Comment by ShengyuH** [comment]
https://github.com/overlappredator/OverlapPredator/issues/9#issuecomment-803964695
