### ISSUE TITLE
Something about the pkl files in /configs

### ISSUE THREAD

**Issue by wra187611** [overlappredator/OverlapPredator#34]
Hello.
I'm just wondering how you prepare the file  train_info.pkl in configs/indoor, I tried to open it and see, there are many names of prepared-to-be-trained pth flies,rotated and translated matrics and overlap ratios, but I don't really know how you organized them(especially the pth files‘ names) and want to know why.
look forward to your reply！
Best wishes！

**Comment by ShengyuH** [comment]
hi,

Assume I have preprocessed dataset(fragments + associated transformation matrix w.r.t. a fixed coordinate framework, please download them and have a look at how they are organised), then I just compute relative transformation matrix(rot + trans) and overlap ratios between any two overlapping pairs and store them as an element in train/val/test_info.pkl. Regarding names, it's scene name from original 3DMatch dataset plus fragment index which doesn't have specific meanings. 

Best,
Shengyu

**Comment by wra187611** [comment]
Thanks!

Maybe I didn't express myself clearly.
I‘m confused about 2 questions:
1.Does the order of the pth files names matters in the pkl files? And is the "order" related to the below transformation matrix?
2.How do you compute relative transformation matrix(rot + trans) and overlap ratios between any two overlapping pairs?Can you give some details or related preprocessing work?

Look forward to your reply!

All the best
Ryan

**Comment by ShengyuH** [comment]
1. sure, see: https://github.com/overlappredator/OverlapPredator/blob/f0e67f887a6c26d5f71ddb963f6dc5efd05888fb/datasets/indoor.py#L45

2. if T_1@X_1 = T_2 @ X_2, then   X_1 = T_1^{-1} @ T_2 @ X_2, so the relative transformation is: T_1^{-1} @ T_2

**Comment by wra187611** [comment]
Thanks for your reply！

I have trained the model for 2 days.And the current model is powerful enough through the given results by your demo code.
However I have a tiny question with the training results.
What is the saliency_loss and why is it keep going up not down?

![image](https://user-images.githubusercontent.com/83273569/142793490-6ee7ce29-4bf1-402a-a276-db1a7cca4443.png)

LOOK FORWARD TO YOUR REPLY!
BEST WISHES!
RYAN

**Comment by lcxiha** [comment]
> hi,
> 
> Assume I have preprocessed dataset(fragments + associated transformation matrix w.r.t. a fixed coordinate framework, please download them and have a look at how they are organised), then I just compute relative transformation matrix(rot + trans) and overlap ratios between any two overlapping pairs and store them as an element in train/val/test_info.pkl. Regarding names, it's scene name from original 3DMatch dataset plus fragment index which doesn't have specific meanings.
> 
> Best, Shengyu

Hi,I would like to know if the fixed coordinate system you are using here refers to the carrier coordinate system (sensor coordinate system) or the global coordinate system?

**Comment by lcxiha** [comment]
> 1. sure, see: https://github.com/overlappredator/OverlapPredator/blob/f0e67f887a6c26d5f71ddb963f6dc5efd05888fb/datasets/indoor.py#L45
> 2. if T_1@X_1 = T_2 @ X_2, then   X_1 = T_1^{-1} @ T_2 @ X_2, so the relative transformation is: T_1^{-1} @ T_2

Hi，Are T_1 and  T_2  transformation matrices relative to the global coordinate system?
