### ISSUE TITLE
Which result is reported in the paper ?

### ISSUE THREAD

**Issue by noone-code** [overlappredator/OverlapPredator#36]
I try to produce the result, could you tell me which result is reported in the paper ?
For example, is the `Inlier ratio  w_mutual`  or the `Inlier ratio wo_mutual` ?

Thank you very much.
: )

-----

Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.656	¦ 0.656	¦ 3.708	¦ 0.091	¦ 524¦
Home 1	¦ 0.496	¦ 0.496	¦ 4.253	¦ 0.108	¦ 283¦
Home 2	¦ 0.572	¦ 0.572	¦ 4.243	¦ 0.108	¦ 222¦
Hotel 1	¦ 0.689	¦ 0.689	¦ 3.804	¦ 0.117	¦ 210¦
Hotel 2	¦ 0.540	¦ 0.540	¦ 3.615	¦ 0.103	¦ 138¦
Hotel 3	¦ 0.610	¦ 0.610	¦ 3.889	¦ 0.080	¦  42¦
Study	¦ 0.407	¦ 0.407	¦ 4.978	¦ 0.149	¦ 237¦
MIT Lab	¦ 0.377	¦ 0.377	¦ 4.067	¦ 0.142	¦  70¦
Mean precision: 0.543: +- 0.105
Weighted precision: 0.567
Mean median RRE: 4.069: +- 0.408
Mean median RTE: 0.112: +- 0.022
`Inlier ratio w_mutual`: 0.221 : +- 0.041
Feature match recall w_mutual: 0.743 : +- 0.090
`Inlier ratio wo_mutual`: 0.171 : +- 0.034
Feature match recall wo_mutual: 0.708 : +- 0.101

**Comment by ShengyuH** [comment]
hi,

- First, please make sure you are using our latest pre-trained model. I don't know your experimental setting but the provided mean precision looks worse than that we report in the paper. 
- Second, to answer your question: as is mentioned in our supplementary material, "Inlier ratio looks at the set of putative correspondences (p, q) ∈ K ij found by reciprocal matchingin feature space,". So Inlier ratio corresponds to ```Inlier ratio w_mutual```.

best,
Shengyu

**Comment by noone-code** [comment]
Thank you so much.
Take it easy, in fact we reproduce a better result than paper.
 The posted result is corresponding to `#Samples=250` in `3DLoMatch`
