### ISSUE TITLE
RANSAC used?

### ISSUE THREAD

**Issue by Aimi-no** [overlappredator/OverlapPredator#39]
Hello,
thank you for your excellent work.
We have been experimenting with Overlap Predator and we have noticed that we get different results for the same input. What implementation of RANSAC did you use? Have you experimented with using other matching algorithms like SuperGlue, Deep MAGSAC...?

Thank you.

**Comment by ShengyuH** [comment]
hi, 

We use RANSAC implemented in open3d, 
- and here's the open3d version:
https://github.com/overlappredator/OverlapPredator/blob/770c3063399f08b3836935212ab4c84d355b4704/requirements.txt#L8
- this is our ransac implementation:
https://github.com/overlappredator/OverlapPredator/blob/770c3063399f08b3836935212ab4c84d355b4704/lib/benchmark_utils.py#L187

Please see this script for more details:
https://github.com/overlappredator/OverlapPredator/blob/main/scripts/evaluate_predator.py

**Comment by Aimi-no** [comment]
Thank you for your reply.
