### ISSUE TITLE
Performance comparison with Mink

### ISSUE THREAD

**Issue by FanLu97** [overlappredator/OverlapPredator#41]
Hello, 
thanks for this excellent work!
I would be grateful if you could help me with the following questions:
1. I observed that you also open-sourced the version with MinkowskiEngine. Have you compared the performance of these two versions? 
2. The voxel size for 3DMatch dataset is 2.5cm and I found that FCGF set voxel size to 5cm. Is there any special reason for using 2.5cm-voxel size? Or have you compared the performance with different voxel size?

Thanks!

**Comment by ShengyuH** [comment]
hi,

Thanks for your interest.

1. see Table 10 in our supp.
2. hmmm I think I just follow D3Feat setting, I didn't really ablate this voxel size. 

best,
Shengyu

**Comment by FanLu97** [comment]
Thanks for your quick reply.
