### ISSUE TITLE
cal_overlap script update

### ISSUE THREAD

**Issue by ttsesm** [overlappredator/OverlapPredator#42]
Hi guys,

Shouldn't the command in this [line](https://github.com/overlappredator/OverlapPredator/blob/770c3063399f08b3836935212ab4c84d355b4704/scripts/cal_overlap.py#L72) be `p.map(cal_overlap_per_scene, base_dir)` instead? Otherwise the `cal_overlap_mat` function is missing or something. 

Also in [line](https://github.com/overlappredator/OverlapPredator/blob/770c3063399f08b3836935212ab4c84d355b4704/scripts/cal_overlap.py#L47) to what is the `03_Transformed` folder corresponds to? For example if I try to apply this on the 3DMatch dataset there is not such a folder.

**Comment by ShengyuH** [comment]
hi,

1. I don't get your point.
2. We didn't update that folder. I provide this script for reference to overlap computation only.

**Comment by ShengyuH** [comment]
Close due to inactivity.
